version: "3.7"

services:
   mysql:
      image: mysql:5.7
      container_name: taskmanager-database
      restart: unless-stopped
      expose:
         - 3306
      ports:
         - ${DB_PORT:-3306}:3306
      volumes:
         - dbmysql:/var/lib/mysql
         - ./docker-compose/mysql:/docker-entrypoint-initdb.d/
      environment:
         MYSQL_ROOT_PASSWORD: rootpassword
         MYSQL_DATABASE: taskmanager
         MYSQL_USER: docker
         MYSQL_PASSWORD: docker
      networks:
         - test-network

   mailhog:
      image: mailhog/mailhog
      logging:
         driver: "none"
      ports:
         - ${MAIL_PORT:-1025}:1025
         - ${MAILHOG_PORT:-8025}:8025
      networks:
         - test-network
networks:
   test-network:
      driver: bridge

volumes:
   dbmysql:
   sail-redis:
      driver: local
